add_rules("mode.debug", "mode.release")
add_requires("sfml")
target("WordWizard")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("sfml")
    set_configdir("$(builddir)/$(plat)/$(arch)/$(mode)")
    add_configfiles("assets/sprites/test_mage/mage/*.png", {onlycopy = true})